name: npm test

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Only Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.dev
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-react
      - name: Test
        run:
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docker-react -f Dockerfile.dev
          docker run ${{ secrets.DOCKERHUB_USERNAME }}/docker-react npm run test -- --coverage
